development:
  sessions:
    default:
      database: gamebot_development
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

test:
  sessions:
    default:
      database: gamebot_test
      hosts:
        - 127.0.0.1:27017
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

production:
  sessions:
    default:
      database: pongbot_production
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true
